### ISSUE TITLE
Apache support

### ISSUE THREAD

**Issue by jfp42** [tomscii/umon#1]
This works on debian:
in /etc/apache2/sites-available/umon.conf
Listen 8888
<VirtualHost *:8888>
  ServerName umon
  #if DOCUMENT_URI is missing, it crashes
  ProxyFCGISetEnvIf "true" DOCUMENT_URI "%{REQUEST_URI}"
  ProxyPass "/" "fcgi://localhost:3333/"
</VirtualHost>

a2ensite umon
systemctl reload apache2

FYI:
This is the crash when DOCUMENT_URI is missing:
(I have not done c++ for over 20 years, so this is as far as I got)
serve_static: uri=''
path: ./static_assets
size: 9223372036854775807
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc

**Comment by tomscii** [comment]
Thanks! Yeah, you won't get anywhere without passing DOCUMENT_URI and QUERY_STRING (the FastCGI params used by umon, as evidenced by a quick glance at the source). Still, it should not crash, but provide a useful error message instead. This is now fixed.
